### ISSUE TITLE
Redux / MobX

### ISSUE THREAD

**Issue by codeheroics** [karakuri-js/karakuri-mobile#16]
I'm starting to feel uncomfortable with the way the app's state is being handled, especially if we start managing a playlist too. Is it time to bring in a way to handle it outside our components?

**Comment by Fenntasy** [comment]
Is this issue still up to date?

**Comment by codeheroics** [comment]
Nope, and I actually tried to close it in a train a few weeks ago, I guess the network was down :)

**Comment by codeheroics** [comment]
(it's done)
