### ISSUE TITLE
Getting the playing content as soon as we log in

### ISSUE THREAD

**Issue by codeheroics** [karakuri-js/karakuri-mobile#41]
Currently, when we log in, we do not get the currently playing content. This means that any user logging in after the karaoke has started needs to wait until the current song is over to get the playlist status bar to display itself correctly.

This is a cross issue with [karakuri-server](https://github.com/karakuri-js/karakuri-server), which probably needs to expose a route to get the currently playing content (or we could expose a "playing" attribute)

**Comment by Fenntasy** [comment]
Shouldn't it just be the first song in the /playlist data?

I'm trying to see that just by reading the code without testing at the moment but it seems logical to me.

**Comment by codeheroics** [comment]
Nope.
Server-side, the randomization code makes it possible that the first song is not the currently playing one. When the song *starts* playing, it is the first song in the /playlist data *for this user* (no guarantee it will be the overall first songs, because the code to decide "fairly" which song will play next does not work that way).

Anyway, as an user may randomize his playlist while his own song is playing, the currently playing song is not even necessarily the first of his song in the playlist. The currently playging song is part of the playlist of "future" songs the server notifies the client about about, and it is actually hidden when we view the playlist client-side (... and as I write this, I think it is kinda dumb, getting the currently playing song out of the "future" playlist would be simpler).

**Comment by Fenntasy** [comment]
So... 

We could revamp that a bit and display the data as scheduled *at the moment*.
Either we send the data with a collection of users with each songs and add the current playing and the next user scheduled or we could send all songs in the order they're supposed to be played right now. What do you think?

I tend to prefer the first solution and we could do a push when a user randomize his playlist.

**Comment by codeheroics** [comment]
So this will be handled in https://github.com/karakuri-js/karakuri-server/issues/43, then the only thing to do here will be to call /playlist when we connect.
