### ISSUE TITLE
Favorites selection & Favorites screen

### ISSUE THREAD

**Issue by codeheroics** [karakuri-js/karakuri-mobile#46]
* Add the ability to mark a song in a favorites list
* Add a favorites screen, which would show all favorite songs.
* Add an favorites import / export mechanism, and make the favorites not device-specific, but user-specific (@Zidrune request).

Identifying songs can be done by using their ids.
The favorites import / export mechanism could work in coordination with karakuri-server, by saving user files on the server.

**Comment by Fenntasy** [comment]
Was wondering if we could use the system to mark songs which ASS need to be updated?
It would require to have a generic list system though 😀

**Comment by codeheroics** [comment]
Actually I think reports should be handled by the server, with a url path like `/report/:id`, which would in turn append to a file named something like `2017-06-16-reports`. Each addition would add to the file the name of the song and an optional comment (so we could report things other than subtitles files needing to be updated, like a video with delayed song), and then the file could just be made available on the server.

I'll create an issue to talk about this.

**Comment by Fenntasy** [comment]
> Add an favorites import / export mechanism, and make the favorites not device-specific, but user-specific

If we save the favorites by user on the server, we don't need an import/export and could do that transparently, no?

**Comment by codeheroics** [comment]
Done :

* Add the ability to mark a song in a favorites list
* Add a favorites screen, which would show all favorite songs.
* Make the favorites not device-specific, but user-specific (@Zidrune request).

Remaining : 
* Add an favorites import / export mechanism.

Closing this in favor of dedicated #65
